#!/bin/sh
# bspwm autostart!!
# keybinds
sxhkd -c ~/.config/bspwm/sxhkdrc -m 1 &
# compositor
compton --config ~/.config/compton.conf --respect-prop-shadow &
# wallpaper
nitrogen --restore &
# panel
$HOME/.config/polybar/launch.sh &
# mpd
mpd &
