#!/bin/sh
#| |
#| |__  ___ _ ____      ___ __ ___
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#| |_) \__ \ |_) \ V  V /| | | | | |
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#          | |
#
# ___〆(・∀・) - It's basically Doom

# === STARTUP ===
# keybinds
sxhkd -c ~/.config/bspwm/sxhkdrc -m 1 &
# compositor
#compton --config ~/.config/compton.conf --respect-prop-shadow &
# wallpaper
nitrogen --restore &
# panel
$HOME/.config/polybar/launch.sh &
# mpd
mpd &
# notifs
dunst &

# === WORKSPACES ===
bspc monitor -d term www chat dev play watch listen work

# windows on play autofloat (probably should move this to another script
bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
	case "$desktop" in
		play)
			bspc node "$nodeid" --state floating
			;;
	esac
done &

# === WINDOWS AND THEIR META ===
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.50

# program rules
# www
bspc rule --add Firefox			    desktop='www' follow=on
# dev
bspc rule --add jetbrains-goland    	    desktop='dev' follow=on
bspc rule --add Code			    desktop='dev' follow=on
# chat
bspc rule --add discord			    desktop='chat'
# play
bspc rule --add Etterna			    desktop='play' follow=on
bspc rule --add Steam			    desktop='play'
# watch
bspc rule --add mpv			    desktop='watch' follow=on
# work
bspc rule --add Gimp			    desktop='work' follow=on
bspc rule --add Surf                	    desktop='work' follow=on
bspc rule --add Zathura             	    desktop='work' follow=on state=tiled
# listen
bspc rule --add Pavucontrol		    desktop='listen' follow=on

# === COLORS ===
bspc config normal_border_color		"#424242"
bspc config active_border_color		"#560088"
bspc config urgent_border_color		"#e83b3f"
