#!/bin/sh
# colors
NORMAL_COLOR="#3b4252"
ACTIVE_COLOR="#4c566a"
URGENT_COLOR="#bf616a"

# workspaces
WS1="term"
WS2="www"
WS3="chat"
WS4="emacs"
WS5="watch"
WS6="listen"
WS7="misc"

start_polybar() {
    killall -u trigex polybar
    # Wait until the processes have been shut down
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    # Launch Polybar
    polybar -r bspwm-bar &
}

start_polybar &
nitrogen --restore &
dunst &
picom &
# application autostarts
emacs &
thelounge &
transmission-gtk &
cantata &

# workspaces
bspc monitor -d "$WS1" "$WS2" "$WS3" "$WS4" "$WS5" "$WS6" "$WS7"

# visuals and stuff
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config normal_border_color "$NORMAL_COLOR"
bspc config active_border_color "$ACTIVE_COLOR"
bspc config urgent_border_color "$URGENT_COLOR"

# window rules
bspc rule -a Firefox desktop="$WS2" follow=on
bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv desktop="$WS5" follow=on
bspc rule -a cantata desktop="$WS6"
bspc rule -a Surf desktop="$WS3"
bspc rule -a '*:emacs' desktop="$WS4"
bspc rule -a Transmission-gtk desktop="$WS7"
