#!/bin/sh
# Compile a given Pandoc Markdown file into a PDF 
cd $HOME/Documents/school
# cli args
DOC=$1

# exit if no documment argument is provided
[ -z "$1" ] && exit

# if no out argument is provided, use a default
[ -z "$2" ] && OUT="out.pdf" || OUT=$2 

# records latest file and output for other scripts
printf "%s\n" "$1" "$2" >> .latest

# sources texlive stuff
#. /etc/profile
# attempt to delete the given output argument file (in case this script is being run over and over, while writing for example)
#rm -f "$OUT"

# TODO: Tweak this to use settings defined in a seperate file
# compile
pandoc "$DOC" -V geometry:a4paper -V geometry:margin=1cm -V mainfont="Dejavu Serif" -V monofont="Operator Mono" -H no_page_num.tex -o "$OUT"

# launch with zathura if zathura isn't already open
[ "$(pidof zathura)" = "" ] && zathura "./$OUT" &
